### ISSUE TITLE
404 error in all the routes

### ISSUE THREAD

**Issue by absolutemadla8** [webprodigies/plura-production#5]
Every route is giving error 404 : This page could not be found.
<img width="1051" alt="Screenshot 2024-02-02 at 12 02 58 PM" src="https://github.com/webprodigies/plura-production/assets/64471611/fc442855-0eed-4b33-b611-66520925f753">

Maybe something to do with shadcn.

**Comment by swarajbachu** [comment]
just put these values in .env

NEXT_PUBLIC_URL=http://localhost:3000
NEXT_PUBLIC_DOMAIN=localhost:3000
NEXT_PUBLIC_SCHEME=http://

**Comment by Suryanandx** [comment]
This didn’t work @swarajbachu  . Any other fixes ?
![Screenshot 2024-02-03 at 21 10 40](https://github.com/webprodigies/plura-production/assets/55799779/56746dc6-ca62-4ab3-97d9-bd79f5edfec5)


I have the same error even after setting up everything

**Comment by absolutemadla8** [comment]
@Suryanandx 
I fixed it by removing afterAuth and customDomain functions from middleware.ts

**Comment by swarajbachu** [comment]
> This didn’t work @swarajbachu . Any other fixes ? ![Screenshot 2024-02-03 at 21 10 40](https://private-user-images.githubusercontent.com/55799779/302045628-56746dc6-ca62-4ab3-97d9-bd79f5edfec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDQzMzksIm5iZiI6MTcwNzAwNDAzOSwicGF0aCI6Ii81NTc5OTc3OS8zMDIwNDU2MjgtNTY3NDZkYzYtY2E2Mi00YWIzLTk3ZDktYmQ3OWY1ZWRmZWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIzNDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzUxZjE3ZThhNDY3NjI5YTIwNWZiZGI1NDgwNzcyZmRiYzNlMzFhZjQ0YTM0MTUwYmI0OWY5NjBiNWQ2MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxf8XPscdXnUkD9P_qoDRpY_1Ivgq0uFCV4H63sUObQ)
> 
> I have the same error even after setting up everything



try adding error.tsx
and make sure you have all your env varibales
removing afterAuth would fix it, but will not redirect you as expeceted
